---
title: "ESM 232 Assignment 2"
author: "Ruben Sanchez Ramirez, Gabe De La Rose, Alex Ehrens"
date: "April 9, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}

# Attach packages
library(tidyverse)
library(janitor)
library(here)
library(ggplot2)
library(kableExtra)
library(formattable)

```

```{r}

# Read in data 
clim_data <- read_table2("clim.txt") %>% 
  clean_names()

```

```{r}

# call the function
source("almond_yield.R")

# run the function using the given climate data
yield_data <- almond_yield(clim_data)

```

```{r}

# Make a table of the variables and calculated yield
table.1 <- yield_data %>% 
  # Add gradient color scale to columns 
  mutate(tmin_c = color_tile("white", "orange")(tmin_c),
         precip = color_tile("white", "orange")(precip),
         yield = color_tile("#DeF7E9", "#71CA97")(yield)) %>% 
  # Rename columns
  rename("Year" = year,
         "Febuary Mean Min Temp(C)" = tmin_c,
         "January Total Precipitation(mm)" = precip,
         "Almond Yield (ton/acre)" = yield) %>% 
  kable(escape = FALSE, align = c("c","c","c","c")) %>% 
  kable_styling() %>% 
  column_spec(1:4, color = "black")
# Call table
table.1

```


```{r fig.asp = 0.9, fig.width = 7, out.width = "100%"}

# Make a plot representing trends
plot.1 <- yield_data %>% 
  ggplot(aes(x = year, y = yield)) +
  geom_line(color = "gray") +
  geom_point(alpha = 0.9,
             shape = 21,
             color = "black",
             aes(size = precip, fill = tmin_c)) +
  scale_size(range = c(5, 20), name = "January Total Precipitation(mm)") +
  scale_fill_gradient(low = "goldenrod1", high = "firebrick",
                      name = "Febuary Mean Min Temp(C)") +
  theme_classic()+
  scale_x_continuous(limits=c(1989, 2010)) +
  scale_y_continuous(limits=c(-1, 2000)) +
  #guides(size = FALSE) +
  #guides(fill = guide_legend(override.aes = list(size = 6))) +
  labs(x = "Harvest Years",
       y = "Almond Yield (ton/acre)") +
  theme(text = element_text(family = "serif"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8),
        legend.text = element_text(size = 8),
        legend.title = element_text(size=8, face="bold"),
        legend.position = "bottom",
        legend.justification = "left",
        legend.box = "vertical", 
        legend.box.just = "left")

plot.1

```



