
---
title: "assignment_3_sanchez-ramirez_ehrens_delarosa"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(janitor)
library(ggplot2)
library(purrr)
```

```{r}

# Read in climate data 
clim_data <- read_table2("clim.txt") %>% 
  clean_names()

```
### Part 1 - Almond Yield Sensitivity Analysis
```{r}

# call the function
source("almond_yield.R")

# make a distribution of the p.coeff2 parameter for uncertainty 
p.coeff2 <- rnorm(n = 500, mean = 0.0043, sd = .001)

# use map_dfr to out put a data frame taking into account all the variability 
yield_data = p.coeff2 %>% 
  map_dfr(~almond_yield( climate = clim_data, p.coeff2 = .x) )

# plot the results using a box plot for uncertainty per year
plot.1 <- yield_data %>% 
  ggplot(aes(x = year, y = yield, group = year)) +
  geom_boxplot(aes(fill = year)) +
  theme_classic()+
  #scale_x_continuous(limits=c(1989, 2010)) +
  scale_y_continuous(limits=c(-1, 2000)) +
  labs(x = "Harvest Years",
       y = "Almond Yield Anomaly (ton/acre)") +
  theme(text = element_text(family = "serif"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8),
        legend.text = element_text(size = 8),
        legend.title = element_text(size=8, face="bold"),
        legend.position = "none")

# view plot
plot.1

# Save plot
ggsave(plot = plot.1, filename = "yield_uncertainty_plot.png", width = 10, height = 7)

```

### Part 2 - NPV of Almond Yield Anomaly
```{r}

# What do we know for NPV function
# Almond production cost $3800/acre (assuming per year)
# Almond profit is $2.50/lb
# Almond production on average is 1 ton/acre/yr
# 2000 lb in 1 ton
# so 2000 lb/acre/yr * $2.50/lb = $5000/acre/yr
# the almond yield function output is in tons/acre

# create a column for profit
yield_data$profit = ((1+yield_data$yield) * 5000) - 3800

# write a function of NPV
NPV_function = function(value, time, discount = 0.12) {
	npv = value / (1 + discount)^time
	return(npv)
}

# create  vector for the number of years we are running the NPV function over
yrs = seq(from = 1, to = length(unique(clim_data$year))-1)

# create a column for year number
yield_data$yrs = rep(yrs, times = 500)

# create a column for the NPV value
yield_data$NPV =  NPV_function(value = yield_data$profit, time = yrs)

# create a box plot
plot.2 <- yield_data %>% 
  ggplot(aes(x = year, y = NPV, group = year)) +
  geom_boxplot(aes(fill = year)) +
  theme_classic()+
  scale_y_continuous(limits=c(-1700, 8000000)) +
  labs(x = "Harvest Years",
       y = "NPV of Almond Yield Anomaly ($)") +
  theme(text = element_text(family = "serif"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8),
        legend.text = element_text(size = 8),
        legend.title = element_text(size=8, face="bold"),
        legend.position = "none")

#view plot
plot.2

# Save plot
ggsave(plot = plot.2, filename = "npv_plot.png", width = 10, height = 7)

```

### END ASSIGNMENT 3